language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install'
script: 'pipenv run make publish'
#after_success:
#  - 'python-codacy-coverage -r coverage.xml'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: output
  on:
    branch: master