name: Deploy Github Pages

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pelican for GitHub Pages
      uses: nelsonjchen/gh-pages-pelican-action@0.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: none #take CNAME from CNAME file
